tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certificates/cert.pem
        keyFile: /certificates/key.pem
  certificates:
    - certFile: /certificates/cert.pem
      keyFile: /certificates/key.pem
      stores:
        - default
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
